/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package random.application;
import java.io.*;
import java.util.Scanner;
/**
 *
 * @author USER
 */
public class Randommhw extends javax.swing.JFrame  {

    /**
     * Creates new form Randommhw
     */
    public Randommhw() throws FileNotFoundException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textbox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ACHL");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try{jButton1MouseClicked(evt);}
                catch(FileNotFoundException file){
                    System.out.println("error");
                }
            }
        });

        jButton2.setText("Oliver");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try{jButton2MouseClicked(evt);}
                catch(FileNotFoundException file){
                    System.out.println("error");
                }
            }
        });

        jButton3.setText("Jacob");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try{jButton3MouseClicked(evt);}
                catch(FileNotFoundException file){
                    System.out.println("error");
                }
            }
        });

        Textbox.setColumns(20);
        Textbox.setRows(5);
        jScrollPane1.setViewportView(Textbox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt)throws FileNotFoundException {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        long end=generate("ACHL");
        Textbox.setText("The generated number is "+end);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt)throws FileNotFoundException {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        long end=generate("Oliver");
        Textbox.setText("The generated number is "+end);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt)throws FileNotFoundException {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
       long end=generate("Jacob");
        Textbox.setText("The generated number is "+end);
    }//GEN-LAST:event_jButton3MouseClicked
public long generate(String x)throws FileNotFoundException{

    long[] array=readfile();
    long result=0;
    if(x=="ACHL"){
        result=Math.round(Math.random()*array[0]);
    }
    if(x=="Oliver"){
        result=Math.round(Math.random()*array[1]);
    }
    if(x=="Jacob"){
        result=Math.round(Math.random()*array[2]);
    }

    if(result==0){
        result=generate(x);
    }
    return result;
}
    /**
     *
     * @return
     */
    public long[] readfile()throws FileNotFoundException{
       File file=new File("C://Users//USER//Downloads//Monster Hunter World Armor Random/data.txt");
       Scanner scan=new Scanner(file);
       long[] array=new long[3];
       array[0]=scan.nextLong();
       array[1]=scan.nextLong();
       array[2]=scan.nextLong();


       return array;


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Randommhw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Randommhw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Randommhw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Randommhw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{new Randommhw().setVisible(true);}
                catch(FileNotFoundException file){
               System.out.println("error");}
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Textbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
